packaging_format = 2

id = "diagramsnet"
name = "Diagrams.net"
description.en = "Diagram software for making flowcharts, process diagrams, org charts"
description.fr = "Application qui permet de faire des schémas et du dessin vectoriel"

version = "32.0.2~ynh1"

maintainers = [ ]

[upstream]
license = "Apache-2.0"
website = "https://www.diagrams.net/"
demo = "https://app.diagrams.net/"
admindoc = "https://www.diagrams.net/doc"
code = "https://github.com/jgraph/drawio"

[integration]
yunohost = ">= 12.1.40"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/diagram"

    [install.init_main_permission]
    type = "group"
    default = "visitors"
[resources]
        [resources.sources.main]
        url = "https://github.com/jgraph/drawio/archive/refs/tags/v32.0.2.tar.gz"
        sha256 = "06124b36a22cec842b44624f6bac74b6d6d100ea0f000f2a1615510b1eabfaf0"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
